### PR TITLE
Added CDN

### PR DESCRIPTION
**Pull request by jimaek**
## Description

Added a CDN link to make the project even faster to use. The included link uses version aliasing /1/ meaning it will auto-update the file to latest 1.x.x version.
The CDN pulls automatically the files from npm. So no need to manually update anything.
Also included a link to browse the file contents in case a user want to load other files, for example from umd/.

## Motivation and Context

Simplify the process of getting started.

## Screenshots (if appropriate):

brite

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Golodhros** [comment]
Hi Jimaek, thanks for the PR!

Actually, if you don't mind, I will defer the merge of this until we fix our issue with the whole bundle (https://github.com/eventbrite/britecharts/issues/186). As that bundle doesn't behave as we would expect, we don't want to publicly advertise our CDN option.

Thanks again!!

**Comment by mking** [comment]
@jimaek @Golodhros Once the whole bundle is ready, consider linking to [unpkg](https://unpkg.com) instead of jsdelivr. unpkg provides CDN access for every package on npm without requiring manual uploads or maintenance.

**Comment by jimaek** [comment]
@mking jsDelivr does the exact same thing https://github.com/jsdelivr/jsdelivr#npm
No maintenance is needed

**Comment by Golodhros** [comment]
Thanks @jimaek , this is working now!

**Pull request merged**
