### PR TITLE
Update example code in bar chart demo

### PR DESCRIPTION
**Pull request by maxbeizer**
## Description
Demo code example had an extra semicolon. This PR removes it.

## Motivation and Context
In trying out the library, I tried the simplest for of spinning it up: copy and paste the demo code. But it's broken.

## How Has This Been Tested?
No. It is not production code, but rather a small fix to the demo.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Golodhros** [comment]
Thanks a lot @maxbeizer !!

**Comment by rwholey-eb** [comment]
Awesome! thank you so mcuh

**Comment by rwholey-eb** [comment]
beat me to it ^^^^

**Comment by Golodhros** [comment]
Hehehe, we were so excited!!

**Pull request merged**
