### PR TITLE
Eventbrite copyright message now appears on bottom of docs pages when printed

### PR DESCRIPTION
**Pull request by cnwalker**
## Description

Previously "Eventbrite Copyright" would appear in the middle of the page overlaid on other elements when a docs page was printed.  Now the page appears on the bottom on Chrome and Firefox and doesn't appear on Safari. 

## Motivation and Context

This fix addresses #228. Also just saw Marcos submitted a PR for this already :(. I'm not sure it's better to just hide it, when we could put it on the bottom of the page so it reflects the webpage as much as possible like the poster in #228 said. 

## How Has This Been Tested?

Built the docs and tested on Chrome, Safari, and Firefox with Mac OSX 10.11.6. 

This change doesn't seem to affect other areas of the code besides the built css after the docs are built.

## Screenshots (if appropriate):
Before:
screen shot 2017-05-15 at 10 53 00 pm

After:
screen shot 2017-05-15 at 10 53 00 pm

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Golodhros** [comment]
@cnwalker !! So glad to have you around!!

I have just created a PR where I remove the footer overall, but I prefer your solution.

Thanks a lot!

**Comment by cnwalker** [comment]
Hahahhahaha good to see you Marcos! I'll be looking to contribute more as classes wind down (and using britecharts for some personal projects). Congrats to on over 2000 stars!

**Comment by Golodhros** [comment]
Thanks buddy! 
You also contributed, so you could claim some of those! :)
Hope your classes were interesting, are you looking for a new internship?

**Comment by cnwalker** [comment]
Hahah, classes are very cool so far. Taking a game construction class this quarter that's particularly good (but a lot of time). I'll be back in the bay area from mid-june to early september working at Box in Redwood City. I'll definitely come and visit Eventbrite!

**Comment by Golodhros** [comment]
Oh, that's nice! I worked some time myself in Redwood city. Box should be great!

Yeah, gaming is hard, but so fun to do Q&A! hahaha

See you in the office pretty soon then!

**Pull request merged**
