### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by bung87**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Golodhros** [comment]
Great! Let's update the docs and ready to merge!

Thanks a lot @bung87 !!

**Comment by bung87** [comment]
@Golodhros docs updated.

**Comment by Golodhros** [comment]
Thanks a lot @bung87 !!

Today I will tackle the other PR for sure!

**Comment by bung87** [comment]
@Golodhros Thanks!,I an very interested in this project,I may make more PRs in next few days until britecharts contains the leaked chart type that list in issues.I am worring about the conflicts with generated docs since it on master branch,so I take out of my hands on this project these days.

**Comment by Golodhros** [comment]
Thanks a lot! 
We are aware of the annoyance of having to build the docs and continually have to update the PRs after something gets merged into master.

We are going to explore the possibility of using Travis to build the docs, maybe that would help.

**Pull request merged**
