### PR TITLE
Added Grid Line Helper

### PR DESCRIPTION
**Pull request by bratter**
Addresses #538. Looking for comments/review on all, but specifically what changes are required to get the jsdoc generation working...

## Description
Provides a grid line helper that using similar logic, API, and transition behavior to the d3 axis. This is a non-breaking change. But it can then be implemented in charts to remove duplicated grid code, which would be breaking.

## Motivation and Context
Addresses #538. Can also be used as a basis for "value axis" helper for #527.

## How Has This Been Tested?
Added `grid.spec.js` to cover incremental functionality

## Types of changes
- [ ] Refactor (changes the way we code something without changing its functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the **CONTRIBUTING** document 
- [x] My code follows the [code style guide](https://github.com/eventbrite/britecharts/blob/master/CODESTYLEGUIDE.md) of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DalerAsrorov** [comment]
Thanks a lot for that, great work! We would need to figure out whether to merge these changes in 3.0 release or current one. As you mentioned, it would break charts if we use these now. Let's see

**Comment by bratter** [comment]
This PR so far is purely additive so won't break anything and could be merged whenever. Future commits that implement this in charts will be breaking and therefore need to go into 3.0.

Cheers

**Comment by DalerAsrorov** [comment]
We should get back to it. Sorry @bratter for keeping this PR hanging. This is impactful change. We will revisit it together with the team (that got smaller 😞  ).

**Comment by bratter** [comment]
No worries - just let me know what you decide re architecture.

**Comment by DalerAsrorov** [comment]
Eh this is a 2 year old PR. Maybe close it now? Sorry

**Comment by Golodhros** [comment]
It is actually included in the version 3 RC, so we can close it, yes.

**Pull request closed without merging**
