### PR TITLE
Feaeture - touchmove event dispatch handlers for Line and StackedArea

### PR DESCRIPTION
**Pull request by dalerasrorov-eb**
## Description
Added `touchmove` custom event handlers for both `Line` and `StackedArea` charts. It can be called and handled without including tooltip.

## Motivation and Context
https://github.com/eventbrite/britecharts/issues/456

## How Has This Been Tested?
Added 1 test each for StackedArea and Line charts that check the `customTouchMove` event handler is dispatched when `touchmove` event is called.

## Screenshots (if appropriate):
`touchmove` for Stacked Area:
barchart_touch_move_stacked_area

`touchmove` for Line:
barchart_touch_move

## Types of changes

- [ ] Refactor (changes the way we code something without changing its functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the [code style guide](https://github.com/eventbrite/britecharts/blob/master/CODESTYLEGUIDE.md) of this project.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ISMAELMARTINEZ** [comment]
Hi @DalerAsrorov, I saw your commit and the change is small so it should just be ok. 

I see there is a bit of inconsistency between the charts functionality mainly due code duplication (or missing between charts). 

I can see that the line chart does handle the "customDataEntryClick" that I assume is the click event, but other charts like the groupbar doesn't implement that part.

Are you planning to share the common functionality between charts? 

Another question is regarding the touchmove event, should it not be also implement the same functionality as the handleMouseMove function (a part from the dispacher)?

Hope helps,

**Comment by Golodhros** [comment]
Hi @ISMAELMARTINEZ, 
'customDataEntryClick' is not a regular click event, is a click in one of the highlight points shown when hovering over the line or stacked area charts. The Bar Chart is the only one that has a 'customClick' event.

I am curious about your use case for having a click on the grouped bar. Still, I think it makes sense to add customClicks to all bar charts.

**Comment by dalerasrorov-eb** [comment]
Will investigate more into adding the `touchmove` to simulate `mousemove`, seems like the API of adding event handlers changed multiple times.

**Comment by ISMAELMARTINEZ** [comment]
@Golodhros, We show energy data for hours/days/weeks/months...  and use the group bar for comparison. 

when you click on the bar you "zoom in" to that part of the day/week/month. That is our usage.

**Comment by Golodhros** [comment]
Thanks @ISMAELMARTINEZ !

I have created an issue for this: https://github.com/eventbrite/britecharts/issues/534

**Comment by dalerasrorov-eb** [comment]
@ISMAELMARTINEZ I have a PR ready https://github.com/eventbrite/britecharts/pull/535, if you have comments feel free to add!

**Pull request merged**
