### PR TITLE
create format helpers

### PR DESCRIPTION
**Pull request by ryanwholey**
Change exponential label format to n-999, 1k-nk format

## Description
The tooltip format looked good, so i extracted it to a format helper, then used that format helper on the line chart y axis

## Motivation and Context
yaxis was showing exponential format instead of 1000s

## How Has This Been Tested?
common helper tested,
no test written for format helper in case we decide to change the formats

screen shot 2017-03-06 at 6 11 32 pm

### CODE REVIEW

**Comment by miglesiasEB** [comment]
This is awesome!!

Could you add it to the Stacked Area Chart too? Just today Nahuel asked me about that same yAxis value format!!

Thanks!!!

**Comment by ryanwholey** [comment]
oh fsho! i'll do that now, thanks!

**Comment by ryanwholey** [comment]
image

**Comment by miglesiasEB** [comment]
Thanks Ryan!

**Pull request merged**
