### PR TITLE
Normalizing chart names between umd and bundle versions. Fixes #288

### LINKED ISSUE #288: Stacked-bar from dist/bundled/britecharts and from dist/umd doesn't work the same
Hello,

The stacked-bar chart from dist/bundled/britecharts.min.js and the stacked-bar from dist/umd/stacked-bar.min.js doesn't work the same

## Expected Behavior
In all case, the stacked-bar constructor should be stackedBar(), for now it's `stacked-bar()` in umd file
`chartContainer.datum(dataset).call(barChart); ` shouldn't trigger an error

## Steps to Reproduce (for bugs)
_Exemple with bundled file_
https://codepen.io/sound-matt/pen/weJdMJ

_Exemple with UMD files_
https://codepen.io/sound-matt/pen/gRPmXK

### PR DESCRIPTION
**Pull request by Golodhros**
## Description
Changing the names on the chart list we use to create the UMD versions of our charts.

## Motivation and Context
Chart names weren't the same on the UMD and bundle versions as described in #288 

## How Has This Been Tested?
Ran tests and bundled production.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Golodhros** [comment]
@ryanwholey This stuff could be annoying for some of our users, but makes sense in the long term.

**Comment by rwholey-eb** [comment]
When do you think would be a good time to land this?

**Comment by Golodhros** [comment]
Any time now, unless you needed the previous fix for the reports!

**Comment by mmartimo** [comment]
Just wanted to check in on the release that includes this...   which as I understand opens up full support via the CDN?   I'm in need of grouped bar charts, pie chart legends, etc...  unless there is a way to access those features via CDN now? (acknowledging that it will need to be updated for the next release)

**Comment by Golodhros** [comment]
Hi @mmartimo,
It could be that the next release takes a bit of time, as we are looking into API changes --explained in https://github.com/eventbrite/britecharts/issues/311.

At this moment, you can check what is included on the CDN repo by following this link: https://cdn.jsdelivr.net/npm/britecharts@1.7.2/dist/umd/

**Pull request merged**
